name: BAP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.0
  - scipy=1.14.1
  - scikit-learn=1.6.0
  - xgboost=2.1.4
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - tqdm=4.66.2
  - joblib=1.4.2
  - pip
  - pip:
      - numba==0.59.1
      - cuml==24.2.0

